config/routes.rb
 Rails.application.routes.draw do

  resources :homes

  resources :drugs do
    collection do
      get 'search'
    end
     resources :reviews, except: [:show, :index]
   end

  resources :users

  resources :diseases

  root 'homes#index'

end

app/models/drug.rb
class Drug < ActiveRecord::Base
	searchkick
	belongs_to :disease
	has_many :reviews
	validates :name, :uses, :sideeffects, :precautions, :interactions, :overdose, :presence=>true 
	has_attached_file :image, styles: { large: "600x600#", medium: "300x300#", thumb: "100x100#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  def search
    if params[:search].present?
      @drugs = Drug.search(params[:search])
    else
      @drugs = Drug.all
    end
  end
  # GET /drugs/1
  # GET /drugs/1.json
  def show
    @reviews = Review.where(drug_id: @drug.id).order("created_at DESC")
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)
    disease = Disease.find(drug_params[:disease_id])
    @drug.build_disease(:id => disease.id)
    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drug_params
      params.require(:drug).permit(:name, :uses, :sideeffects, :precautions, :interactions, :overdose, :disease_id, :image)
    end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_for @drug, :html => { :multipart => true } do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
 <%= f.label :disease_id %><br>
 <%= f.select :disease_id, 
options_for_select(Disease.all.collect {|a| ["#{a.name}", a.id]}, selected: (@drug.disease ? @drug.disease.id : Disease.first.id)), {} %>
</div>
  <div class="field">
    <%= f.label :uses %><br>
    <%= f.text_area :uses %>
  </div>
  <div class="field">
    <%= f.label :sideeffects %><br>
    <%= f.text_area :sideeffects %>
  </div>
  <div class="field">
    <%= f.label :precautions %><br>
    <%= f.text_area :precautions %>
  </div>
  <div class="field">
    <%= f.label :interactions %><br>
    <%= f.text_area :interactions %>
  </div>
  <div class="field">
    <%= f.label :overdose %><br>
    <%= f.text_area :overdose %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div></div>
<div class="row">
  <% @drugs.each do |drug| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag drug.image.url(:medium), class:'image'),drug%>
      </div>
    </div>
  <% end %>
</div>
<span class="btn"><%= link_to 'New Drug', new_drug_path %></span>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form' %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/search.html.erb
<div class="row">
  <% @drugs.each do |drug| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag drug.image.url(:medium), class:'image'),drug%>
      </div>
    </div>
  <% end %>
</div>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @drug.image.url(:medium) %>
        <p>
          <strong>Name:</strong>
          <%= @drug.name %>
        </p>
        <p>
         <strong>Disease:</strong>
         <%= (@drug.disease.try(:name) || "NA")%>
        </p>
        <p>
          <strong>Uses:</strong>
          <%= @drug.uses %>
        </p>

        <p>
          <strong>Sideeffects:</strong>
          <%= @drug.sideeffects %>
        </p>

        <p>
          <strong>Precautions:</strong>
          <%= @drug.precautions %>
        </p>

        <p>
          <strong>Interactions:</strong>
          <%= @drug.interactions %>
        </p>

        <p>
          <strong>Overdose:</strong>
          <%= @drug.overdose %>
        </p>
        <%= link_to "Write a Review", new_drug_review_path(@drug) %>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @drug.name %></h1>
        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_drug_review_path(@drug), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">              
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>